global using AccessMod.Models.OAuthDtos;
global using Entity.AccessMod;
global using Entity.CommonMod;
global using EntityFramework.AppDbContext;
global using EntityFramework.AppDbFactory;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Perigon.AspNetCore.Abstraction;
global using Perigon.AspNetCore.Models;
// global using AccessMod.Managers;
global using Perigon.AspNetCore.Utils;
global using Share.Implement;
global using Share.Services;
global using System.ComponentModel.DataAnnotations;
global using static AccessMod.OAuthConstants;
