global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics;
global using System.Linq.Expressions;
// global using IdentityMod.Managers;
global using Ater.Web.Convention;
global using Ater.Common.Models;
global using Ater.Common.Utils;
global using Ater.Web.Extension;
global using Entity;
global using Entity.IdentityMod;
global using EntityFramework;
global using EntityFramework.DBProvider;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;