global using System.ComponentModel.DataAnnotations;
global using Ater.Common.Models;
global using Ater.Common.Utils;
global using Entity.AccessMod;
global using Entity.IdentityMod;
global using EntityFramework.DBProvider;
global using IdentityMod.Managers;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Share.Implement;
global using Share.Services;
global using static IdentityMod.OAuthConstants;