global using Entity.IAMMod;
global using IAMMod;
global using Microsoft.AspNetCore.Mvc;
global using Perigon.AspNetCore.Abstraction;
global using Perigon.AspNetCore.Constants;
global using Perigon.AspNetCore.Models;
global using Perigon.AspNetCore.Utils;
global using ServiceDefaults;
global using ServiceDefaults.Middleware;
global using Share;
global using Share.Constants;
global using Share.Implement;
global using static Share.Constants.OAuthConst;
