// This file is generated by scripts/i18n-keys.js
// Do not edit this file directly.
/* eslint-disable */
export const I18N_KEYS = {
  "app": {
    "brand": "app.brand",
    "title": "app.title"
  },
  "language": {
    "label": "language.label",
    "zh": "language.zh",
    "en": "language.en"
  },
  "common": {
    "ok": "common.ok",
    "close": "common.close",
    "loading": "common.loading",
    "notAvailable": "common.notAvailable",
    "unknownError": "common.unknownError",
    "publicPermission": "common.publicPermission"
  },
  "navigation": {
    "toggle": "navigation.toggle",
    "home": "navigation.home",
    "protected": "navigation.protected",
    "authorizations": "navigation.authorizations",
    "currentSession": "navigation.currentSession"
  },
  "session": {
    "guest": "session.guest",
    "user": "session.user",
    "notLoggedIn": "session.notLoggedIn",
    "loginHint": "session.loginHint",
    "loadedPermissions": "session.loadedPermissions"
  },
  "auth": {
    "login": "auth.login",
    "logout": "auth.logout",
    "initializing": "auth.initializing",
    "loginStatus": "auth.loginStatus",
    "loggedIn": "auth.loggedIn",
    "loggedOut": "auth.loggedOut"
  },
  "home": {
    "userInfoTitle": "home.userInfoTitle",
    "userInfoSubtitle": "home.userInfoSubtitle",
    "name": "home.name",
    "email": "home.email",
    "userId": "home.userId",
    "permissionsTitle": "home.permissionsTitle",
    "permissionsSubtitle": "home.permissionsSubtitle",
    "loadingPermissions": "home.loadingPermissions",
    "noPermissions": "home.noPermissions",
    "permissionType": "home.permissionType",
    "permissionClient": "home.permissionClient"
  },
  "callback": {
    "title": "callback.title",
    "pending": "callback.pending",
    "failedRedirecting": "callback.failedRedirecting"
  },
  "unauthorized": {
    "title": "unauthorized.title",
    "message": "unauthorized.message",
    "hint": "unauthorized.hint",
    "backHome": "unauthorized.backHome"
  },
  "protected": {
    "title": "protected.title",
    "loadingUser": "protected.loadingUser",
    "name": "protected.name",
    "email": "protected.email",
    "userId": "protected.userId",
    "viewClaims": "protected.viewClaims",
    "apiTestTitle": "protected.apiTestTitle",
    "apiTestSubtitle": "protected.apiTestSubtitle",
    "callPublicApi": "protected.callPublicApi",
    "callProtectedApi": "protected.callProtectedApi",
    "callWeatherApi": "protected.callWeatherApi",
    "apiResponse": "protected.apiResponse",
    "publicApiSuccess": "protected.publicApiSuccess",
    "publicApiError": "protected.publicApiError",
    "protectedApiSuccess": "protected.protectedApiSuccess",
    "protectedApiError": "protected.protectedApiError",
    "weatherSuccess": "protected.weatherSuccess",
    "weatherError": "protected.weatherError",
    "errors": {
      "unauthorized401": "protected.errors.unauthorized401",
      "forbidden403": "protected.errors.forbidden403",
      "apiUnavailable": "protected.errors.apiUnavailable"
    }
  },
  "authorizations": {
    "title": "authorizations.title",
    "subtitle": "authorizations.subtitle",
    "empty": "authorizations.empty",
    "clientId": "authorizations.clientId",
    "scopes": "authorizations.scopes",
    "createdAt": "authorizations.createdAt",
    "expiresAt": "authorizations.expiresAt",
    "neverExpires": "authorizations.neverExpires",
    "revoke": "authorizations.revoke",
    "revokeSuccess": "authorizations.revokeSuccess",
    "loadFailed": "authorizations.loadFailed",
    "revokeFailed": "authorizations.revokeFailed",
    "confirmTitle": "authorizations.confirmTitle",
    "confirmMessage": "authorizations.confirmMessage",
    "confirmHint": "authorizations.confirmHint",
    "cancel": "authorizations.cancel",
    "confirmRevoke": "authorizations.confirmRevoke",
    "types": {
      "permanent": "authorizations.types.permanent",
      "adHoc": "authorizations.types.adHoc"
    },
    "statuses": {
      "valid": "authorizations.statuses.valid",
      "revoked": "authorizations.statuses.revoked"
    }
  }
};
