global using Entity.IAMMod;
global using EntityFramework.AppDbContext;
global using EntityFramework.AppDbFactory;
global using IAMMod.Models.OAuthDtos;
global using IAMMod.Services;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Perigon.AspNetCore.Abstraction;
global using Perigon.AspNetCore.Constants;
global using Perigon.AspNetCore.Converters;
global using Perigon.AspNetCore.Models;
global using Perigon.AspNetCore.Options;
// global using IAMMod.Managers;
global using Perigon.AspNetCore.Utils;
global using ServiceDefaults;
global using Share;
global using Share.Constants;
global using Share.Implement;
global using System.ComponentModel.DataAnnotations;
global using static Share.Constants.OAuthConst;
