global using System.Linq.Expressions;
global using Perigon.AspNetCore.Options;
global using Perigon.AspNetCore.Abstraction;
global using Entity;
global using Entity.AccessMod;
global using Entity.CommonMod;
global using Entity.IdentityMod;
global using Microsoft.EntityFrameworkCore;
global using EntityFramework.Extensions;
