global using System;
global using EntityFramework.AppDbContext;
global using EntityFramework.AppDbFactory;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Perigon.AspNetCore.Abstraction;
global using Perigon.AspNetCore.Constants;
global using Perigon.AspNetCore.Models;
global using Perigon.AspNetCore.Utils;
